verbes = {'arise': ('arise', 'arose', 'arisen'), 'awak': ('awak', 'awok', 'awoken'),
          'be': (' be', ' was/were', ' been'),
          'beat': (' beat', ' beat', ' beaten'), 'become': ('become', 'became', 'become'),
          'begin': ('begin', 'began', 'begun'),
          'bend': (' bend', ' bent', ' bent'), 'bet': ('bet ', 'bet ', 'bet '),
          "bite": (' bite', ' bit', ' bitten'),
          'blow': ('blow', 'blew', 'blown'), 'break': ('break', 'broke', 'broken'),
          'bring': ('bring', 'brought', 'brought'),
          'build': ('build', 'built', 'built'), 'burn': ('burn', 'burned', 'burned'),
          'burst': ('burst', 'burst', 'burst'),
          'buy': ('buy', 'bought', 'bought'), 'catch': ('catch', 'caught', 'caught'),
          'choose': ('choose', 'chose', 'chosen'),
          'come': ('come', 'came', 'come'), 'creep': ('creep', 'crept', 'crept'), 'cost': ('cost', 'cost', 'cost'),
          'cut': ('cut', 'cut', 'cut'), 'deal': ('deal', 'dealt', 'dealt'), 'big': ('dig', 'dug', 'dug'),
          'do': ('do', 'did', 'done'),
          'draw': ('draw', 'drew', 'drawn'), 'drink': ('drink', 'drank', 'drunk'),
          'drive': ('drive', 'drove', 'driven'),
          'eat': ('eat', 'ate', 'eaten'), 'fall': ('fall', 'fell', 'fallen'), 'feed': ('feed', 'fed', 'fed'),
          'feel': ('feel', 'felt', 'felt'),
          'fight': ('fight', 'fought', 'fought'), 'find': ('find', 'found', 'found'), 'fit': ('fit', 'fit', 'fit'),
          'fly': ('fly', 'flew', 'flown'), 'forbid': ('forbid', 'forbade', 'forbidden'),
          'forget': ('forget', 'forgot', 'forgotten'),
          'forgive': ('forgive', 'forgave', 'forgiven'), 'freeze': ('freeze', 'froze', 'frozen'),
          'get': ('get', 'got', 'got'),
          'give': ('give', 'gave', 'given'), 'go': ('go', 'went', 'gone'), 'grow': ('grow', 'grew', 'grown'),
          'hang': ('hang', 'hung', 'hung'),
          'have': ('have', 'had', 'had'), 'hear': ('hear', 'heard', 'heard'), 'hide': ('hide', 'hid', 'hidden'),
          'hit': (' hit', ' hit', ' hit'),
          'hold': ('hold', 'held', 'held'), 'hurt': ('hurt', 'hurt', 'hurt'), 'keep': ('keep', 'kept', 'kept'),
          'kneel': ('kneel', 'knelt', 'knelt'),
          'know': ('know', 'knew', 'known'), 'lay': ('lay', 'laid', 'laid'), 'lead': ('lead', 'led', 'led'),
          'learn': ('learn', 'learned', 'learned'),
          'leave': ('leave', 'left', 'left'), 'lend': ('lend', 'lent', 'lent'), 'let': ('let', ' let', ' let'),
          'lie': ('lie', 'lay''lain'), 'light': ('light', 'lit/lighted', 'lit/lighted'),
          'lose': (' lose', ' lost', ' lost'),
          'make': (' make', ' made', ' made'), 'mean': ('mean', 'meant', 'meant'), 'meet': ('meet', 'met', 'met'),
          'pay': ('pay', 'paid', 'paid'),
          'put': ('put', 'put', 'put'), 'read': ('read', 'read', 'read'), 'ride': ('ride', 'rode', 'ridden'),
          'ring': ('ring', 'rang', 'rung'), 'rise': ('rise', 'rose', 'risen'), 'run': ('run', 'ran', 'run'),
          'say': ('say', 'said', 'said'), 'see': ('see', 'saw', 'seen'), 'seek': ('seek', 'sought', 'sought'),
          'sell': ('sell', 'sold', 'sold'), 'send': ('send', 'sent', 'sent'), 'set': ('set', 'set', 'set'),
          'sew': ('sew', 'sewed', 'sewed/sewn'),
          'shake': ('shake', 'shook', 'shaken'), 'shine': ('shine', 'shone', 'shone'),
          'shoot': ('shoot', 'shot', 'shot'),
          'show': ('show', 'showed', 'shown'), 'shrink': ('shrink', 'shrank', 'shrunk'),
          'shut': ('shut', 'shut', 'shut'),
          'sing': ('sing', 'sang', 'sung'), 'sink': ('sink', 'sank', 'sunk'), 'sit': ('sit ', 'sat ', 'sat '),
          'sleep': ('sleep ', 'slept ', 'slept '),
          'smell': ('smell', 'smelled', 'smelled'), 'speak': ('speak', 'spoke', 'spoken'),
          'spend': ('spend', 'spent', 'spent'),
          'split': ('split', 'split', 'split'), 'spread': ('spread', 'spread', 'spread'),
          'spring': ('spring', 'sprang', 'sprung'),
          'stand': ('stand', 'stood', 'stood'), 'steal': ('steal', 'stole', 'stolen'),
          'stick': ('stick', 'stuck', 'stuck'),
          'sting': ('sting', 'stang', 'stung'), 'stink': ('stink', 'stank', 'stunk'),
          'strike': ('strike', 'struck', 'struck'),
          'swear': ('swear', 'swore', 'sworn'), 'sweep': ('sweep', 'swept', 'swept'),
          'swell': ('swell', 'swelled', 'swollen'),
          'swim': ('swim', 'swam', 'swum'), 'swing': ('swing', 'swung', 'swung'), 'take': ('take', 'took', 'taken'),
          'teach': ('teach', 'taught', 'taught'), 'tear': ('tear', 'tore', 'torn'),
          'tell': ('tell', 'told', 'told'),
          'think': ('think', 'thought', 'thought'), 'throw': ('throw', 'threw', 'thrown'),
          'understand': ('understand', 'understood', 'understood'), 'wake': ('wake', 'woke', 'woken'),
          'wear': ('wear', 'wore', 'worn'),'weep': ('weep', ' wept', ' wept'), 'win': (' win', ' won', ' won'),
          'write': ('write', 'wrote', 'written')}

items = ['arise', 'arose', 'arisen', 'awak', 'awok', 'awoken', ' be', ' was/were', ' been',
         ' beat', ' beat', ' beaten', 'become', 'became', 'become', 'begin', 'began', 'begun',
         ' bend', ' bent', ' bent', 'bet ', 'bet ', 'bet ', ' bite', ' bit', ' bitten',
         'blow', 'blew', 'blown',

         'break', 'broke', 'broken', 'bring', 'brought', 'brought', 'build', 'built', 'built',
         'burn', 'burned', 'burned', 'burst', 'burst', 'burst', 'buy', 'bought', 'bought',
         'catch', 'caught', 'caught', 'choose', 'chose', 'chosen', 'come', 'came', 'come',
         'creep', 'crept', 'crept',

          'cost', 'cost', 'cost', 'cut', 'cut', 'cut', 'deal', 'dealt', 'dealt', 'dig', 'dug', 'dug',
          'do', 'did', 'done', 'draw', 'drew', 'drawn', 'drink', 'drank', 'drunk',
          'drive', 'drove', 'driven', 'eat', 'ate', 'eaten', 'fall', 'fell', 'fallen',

          'feed', 'fed', 'fed', 'feel', 'felt', 'felt', 'fight', 'fought', 'fought', 'find', 'found', 'found',
          'fit', 'fit', 'fit', 'fly', 'flew', 'flown', 'forbid', 'forbade', 'forbidden',
          'forget', 'forgot', 'forgotten', 'forgive', 'forgave', 'forgiven', 'freeze', 'froze', 'frozen',

          'get', 'got', 'got', 'give', 'gave', 'given', 'go', 'went', 'gone',
          'grow', 'grew', 'grown', 'hang', 'hung', 'hung', 'have', 'had', 'had',
          'hear', 'heard', 'heard', 'hide', 'hid', 'hidden', ' hit', ' hit', ' hit', 'hold', 'held', 'held',

          'hurt', 'hurt', 'hurt', 'keep', 'kept', 'kept', 'kneel', 'knelt', 'knelt',
          'know', 'knew', 'known', 'lay', 'laid', 'laid', 'lead', 'led', 'led',
          'learn', 'learned', 'learned', 'leave', 'left', 'left', 'lend', 'lent', 'lent',
          ' let', ' let', ' let',

          'lie', 'lay','lain', 'light', 'lit/lighted', 'lit/lighted', ' lose', ' lost', ' lost',
          ' make', ' made', ' made',
          'mean', 'meant', 'meant', 'meet', 'met', 'met', 'pay', 'paid', 'paid',
          ' put', ' put', ' put', 'read', 'read', 'read', 'ride', 'rode', 'ridden',

          'ring', 'rang', 'rung', 'rise', 'rose', 'risen', 'run', 'ran', 'run',
          'say', 'said', 'said', 'see', 'saw', 'seen', 'seek', 'sought', 'sought',
          'sell', 'sold', 'sold', 'send', 'sent', 'sent', 'set', 'set', 'set', 'sew', 'sewed', 'sewed/sewn',

          'shake', 'shook', 'shaken', 'shine', 'shone', 'shone', 'shoot', 'shot', 'shot',
          'show', 'showed', 'shown', 'shrink', 'shrank', 'shrunk', 'shut', 'shut', 'shut',
          'sing', 'sang', 'sung', 'sink', 'sank', 'sunk', 'sit ', 'sat ', 'sat ', 'sleep ', 'slept ', 'slept ',

          'smell', 'smelled', 'smelled', 'speak', 'spoke', 'spoken', 'spend', 'spent', 'spent',
          'split', 'split', 'split', 'spread', 'spread', 'spread', 'spring', 'sprang', 'sprung',
          'stand', 'stood', 'stood', 'steal', 'stole', 'stolen', 'stick', 'stuck', 'stuck',
          'sting', 'stang', 'stung',

          'stink', 'stank', 'stunk', 'strike', 'struck', 'struck', 'swear', 'swore', 'sworn',
          'sweep', 'swept', 'swept',
          'swell', 'swelled', 'swollen', 'swim', 'swam', 'swum', 'swing', 'swung', 'swung',
          'take', 'took', 'taken',
          'teach', 'taught', 'taught', 'tear', 'tore', 'torn',
          'tell', 'told', 'told', 'think', 'thought', 'thought', 'throw', 'threw', 'thrown',
          'understand', 'understood', 'understood', 'wake', 'woke', 'woken', 'wear', 'wore', 'worn',
          ' weep', ' wept', ' wept', ' win', ' won', ' won', 'write', 'wrote', 'written']